import{captureFlight,postflight,addMin,json,isCancelled,trackLooksTerminated}from"./lib.js";import{claimDueCheckpoints,saveCapture,checkpointState,rescheduleCheckpoint,retryCheckpoint,closeoutEligibility,saveTrack,latestEligibleBaseline,saveScores,finishJob,getJob,terminalize,markScoreable}from"./db.js";import{methodA}from"./score.js";
const CONCURRENCY=6,RETRY_DELAY_MS=60000,RETRY_WINDOW_MS=180000,MAX_TRANSIENT_ATTEMPTS=3,RETRY_PREFIX="TRANSIENT_RETRY:";
function postflightDeadline(job){const base=job.scheduled_on_initial||new Date(new Date(job.scheduled_out_initial).getTime()+180*60000).toISOString();return new Date(new Date(base).getTime()+6*3600000);}
function retryMeta(cp){const t=String(cp.error_text||"");if(!t.startsWith(RETRY_PREFIX))return null;try{const x=JSON.parse(t.slice(RETRY_PREFIX.length));if(Number.isFinite(x.started)&&Number.isInteger(x.failures)&&x.failures>0)return x;}catch{}return null;}
export function isTransientError(e){const status=Number(e?.status);if([500,502,503,504].includes(status))return true;if(status)return false;const code=String(e?.code||e?.cause?.code||"").toUpperCase(),name=String(e?.name||"").toUpperCase(),msg=String(e?.message||"").toUpperCase();return["ECONNRESET","ETIMEDOUT","ECONNREFUSED","EAI_AGAIN","UND_ERR_CONNECT_TIMEOUT","UND_ERR_SOCKET"].some(x=>code.includes(x)||msg.includes(x))||name==="ABORTERROR"||name==="TIMEOUTERROR"||/NETWORK|FETCH FAILED|SOCKET HANG UP/.test(msg);}
function errorText(e){return String(e?.message||e||"transient error").slice(0,500);}
export function retryDecision(cp,e,nowMs=Date.now()){if(!isTransientError(e))return{action:"THROW"};const prior=retryMeta(cp),started=prior?.started??nowMs,failures=(prior?.failures??0)+1;if(nowMs-started>=RETRY_WINDOW_MS)return{action:"STOP",reason:"CHECKPOINT_WINDOW_CLOSED",started,failures};if(failures>=MAX_TRANSIENT_ATTEMPTS)return{action:"STOP",reason:"MAX_ATTEMPTS_REACHED",started,failures};return{action:"RETRY",started,failures,due:new Date(nowMs+RETRY_DELAY_MS).toISOString()};}
async function apiCall(cp,fn){try{return{ok:true,value:await fn()};}catch(e){const d=retryDecision(cp,e);if(d.action==="THROW")throw e;if(d.action==="STOP"){await checkpointState(cp.id,"ERROR",null,`${d.reason}: ${errorText(e)}`);return{ok:false,event:{flight:cp.fa_flight_id,label:cp.label,state:d.reason,error:errorText(e)}};}const marker=RETRY_PREFIX+JSON.stringify({started:d.started,failures:d.failures});await retryCheckpoint(cp.id,d.due,marker);return{ok:false,event:{flight:cp.fa_flight_id,label:cp.label,state:"RETRY_SCHEDULED",retry_in_seconds:60,transient_attempt:d.failures,next_due:d.due,error:errorText(e)}};}}
async function processOne(cp){const job=await getJob(cp.flight_job_id);if(!job)return{flight:cp.fa_flight_id,label:cp.label,state:"NO_JOB"};
 if(cp.label==="POSTFLIGHT"){
   const got=await apiCall(cp,()=>postflight(cp.fa_flight_id));if(!got.ok)return got.event;const pf=got.value;
   if(isCancelled(pf.flight.status)&&!pf.flight.actual_out){await terminalize(job.id,"CANCELLED","AeroAPI cancellation before actual_out","CANCELLED");return{flight:cp.fa_flight_id,label:"POSTFLIGHT",state:"CANCELLED"};}
   if(isCancelled(pf.flight.status)&&pf.flight.actual_out&&!pf.flight.actual_on){await terminalize(job.id,"IRREGULAR_NONCOMPLETION","AeroAPI cancellation/irregular completion after actual_out");return{flight:cp.fa_flight_id,label:"POSTFLIGHT",state:"IRREGULAR_NONCOMPLETION"};}
   if(new Date()>postflightDeadline(job)&&(!pf.flight.actual_on||!trackLooksTerminated(pf))){await terminalize(job.id,"POSTFLIGHT_UNAVAILABLE","actual_on or terminated track unavailable by scheduled_on_initial + 6h");return{flight:cp.fa_flight_id,label:"POSTFLIGHT",state:"POSTFLIGHT_UNAVAILABLE"};}
   if(!pf.flight.actual_on||!trackLooksTerminated(pf)){await rescheduleCheckpoint(cp.id,addMin(new Date().toISOString(),15));return{flight:cp.fa_flight_id,label:"POSTFLIGHT",state:"RESCHEDULED",actual_on:pf.flight.actual_on,track_count:pf.track.count,track_last:pf.track.last};}
   const realized=String(pf.flight.destination||"").toUpperCase(),frozen=String(job.destination||"").toUpperCase();
   if(realized&&frozen&&realized!==frozen){await terminalize(job.id,"DIVERTED",`realized destination ${realized} differs from frozen destination ${frozen}`);return{flight:cp.fa_flight_id,label:"POSTFLIGHT",state:"DIVERTED",frozen_destination:frozen,realized_destination:realized};}
   if(pf.flight.actual_out)await closeoutEligibility(job.id,pf.flight.actual_out);
   const tr=await saveTrack(job.id,pf),base=await latestEligibleBaseline(job.id);let means=null;
   await markScoreable(job.id);
   if(base){const raw=base.raw_capture,bpts=(raw.protocol?.fixes||[]).filter(x=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)),apts=pf.track.points.filter(x=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude));if(bpts.length>1&&apts.length>1)means=await saveScores(job.id,base.id,tr.id,methodA(bpts,apts));}
   await finishJob(job.id,pf);await checkpointState(cp.id,"COMPLETE",pf.captured_at);return{flight:cp.fa_flight_id,label:"POSTFLIGHT",state:"COMPLETE",terminal_state:"SCOREABLE",means};
 }
 const got=await apiCall(cp,()=>captureFlight(cp.fa_flight_id));if(!got.ok)return got.event;const c=got.value;
 if(isCancelled(c.flight.status)&&!c.flight.actual_out){await terminalize(job.id,"CANCELLED","AeroAPI cancellation before actual_out","CANCELLED");return{flight:cp.fa_flight_id,label:cp.label,state:"CANCELLED"};}
 if(isCancelled(c.flight.status)&&c.flight.actual_out){await terminalize(job.id,"IRREGULAR_NONCOMPLETION","AeroAPI cancellation/irregular completion after actual_out");return{flight:cp.fa_flight_id,label:cp.label,state:"IRREGULAR_NONCOMPLETION"};}
 await saveCapture(job.id,cp.id,c);if(c.flight.actual_out)await closeoutEligibility(job.id,c.flight.actual_out);
 if(cp.label==="DELAY"){if(c.flight.actual_out){await checkpointState(cp.id,"STOPPED",c.captured_at);return{flight:cp.fa_flight_id,label:"DELAY",state:"STOPPED",actual_out:c.flight.actual_out};}await rescheduleCheckpoint(cp.id,addMin(new Date().toISOString(),15));return{flight:cp.fa_flight_id,label:"DELAY",state:"RESCHEDULED"};}
 await checkpointState(cp.id,"CAPTURED",c.captured_at);return{flight:cp.fa_flight_id,label:cp.label,state:"CAPTURED",hash:c.protocol.canonical_hash,actual_out_seen:c.flight.actual_out,captured_at:c.captured_at};
}
export default async function handler(req,res){const events=[];try{const due=await claimDueCheckpoints(CONCURRENCY);const settled=await Promise.allSettled(due.map(processOne));for(let k=0;k<settled.length;k++){const x=settled[k],cp=due[k];if(x.status==="fulfilled")events.push(x.value);else{await checkpointState(cp.id,"ERROR",null,x.reason?.message||String(x.reason));events.push({flight:cp.fa_flight_id,label:cp.label,state:"ERROR",error:x.reason?.message||String(x.reason)});}}json(res,200,{ok:true,processed:events.length,concurrency:CONCURRENCY,events});}catch(e){json(res,500,{ok:false,error:e.message,events})}}
